In [2]:
import numpy as np  
mylist = [1,2,3]

print(type(mylist))

<class 'list'>


In [5]:
myarray = np.array(mylist)
print(myarray)


[1 2 3]


In [6]:
print(type(myarray))

<class 'numpy.ndarray'>


In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
type(0)

int

In [13]:
type(0.)

float

In [14]:
np.ones(shape = (2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [18]:
arr2 = np.random.randint(0,100,10)

In [19]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [20]:
arr.max() # return the maximum number from the array.

95

In [21]:
arr.argmax() # returns the index of the maximum element

0

In [22]:
arr.min()

9

In [24]:
arr.argmin()

7

In [25]:
arr.mean()

60.8

In [30]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [31]:
mat = np.arange(0,100).reshape((10,10))
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
mat.shape


(10, 10)

In [35]:
row = 0
col = 1
mat[row,col]

1

In [36]:
mat[4,6]

46

In [39]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
mat[:,1].shape

(10,)

In [42]:
mat[:,1].reshape((1,10))

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [43]:
mat[:,1].reshape((10,1))

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [44]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [46]:
mynewmat = mat.copy()

In [47]:
mynewmat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
mynewmat[:6,:] = 99

In [51]:
mynewmat

array([[99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])